resources:

- name: kubernetes-resource
  type: git
  source:
    uri: git://github.com/jeffellin/kubernetes-resource.git
    branch: master


- name: kubernetes-resource-image
  type: docker-image
  source:
    repository: harbor.ellin.net:443/library/kubernetes-resource
    username: jeff
    password: ((harbor.password))
    insecure_registries:
      - harbor.ellin.net:443

jobs:
- name: build-kubernetes-resource-image
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource
        trigger: true
    - put: kubernetes-resource-image
      params:
        build: kubernetes-resource
